### ISSUE TITLE
fill doesn't work

### ISSUE THREAD

**Issue by Jeb4dev** [JesperKauppinen/paint-webapp#10]
fill function doesnt work and leads to an error:
`Uncaught TypeError: drawFunctions[shape] is not a function`
![image](https://user-images.githubusercontent.com/76889226/144337644-e42d1b51-1126-49ed-99bd-ca5195f6f25a.png)

function in canvas-utils.js 
![image](https://user-images.githubusercontent.com/76889226/144337622-cb133a3d-21f5-48e9-bf76-cad0aef347b2.png)

**Comment by mihett05** [comment]
Fixed
